// קטלוג שלושת הסטים. המחירים ניתנים לעדכון כאן לאחר קביעת המחיר הסופי.
let products = [
 {id:1,sku:'SEF-001',type:'סט',name:'סט ספרדי מהודר',desc:'סט ארבעת המינים מהודר בנוסח הספרדים — אתרוג, לולב, הדסים וערבות, נבחר ונארז בקפידה.',price:130,badge:'ספרדי מהודר',level:'מהודר',variety:'ספרדי',icon:'fa-leaf'},
 {id:2,sku:'ASH-001',type:'סט',name:'סט אשכנזי מהודר',desc:'סט ארבעת המינים מהודר בנוסח אשכנז — אתרוג, לולב, הדסים וערבות, נבחר ונארז בקפידה.',price:130,badge:'אשכנזי מהודר',level:'מהודר',variety:'אשכנזי',icon:'fa-leaf'},
 {id:3,sku:'YEM-001',type:'סט',name:'סט ספרדי עם אתרוג תימני',desc:'סט ספרדי מהודר עם אתרוג תימני, לולב, הדסים וערבות — נבחר ונארז בקפידה.',price:130,badge:'אתרוג תימני',level:'מהודר',variety:'ספרדי · אתרוג תימני',icon:'fa-leaf'}
];
let cart=JSON.parse(localStorage.getItem('sukkot_cart'))||[];
const ORDER_SEQUENCE_KEY='sukkot_order_sequence';
let isSubmittingOrder=false;

document.addEventListener('DOMContentLoaded',()=>{renderProducts();updateCartUI();addSpecialOrderBanner();});
function toggleMenu(){document.getElementById('navMenu')?.classList.toggle('mobile-open');}
function openCartModal(){document.getElementById('cartModal')?.classList.add('active');renderCartItems();}
function closeCartModal(){document.getElementById('cartModal')?.classList.remove('active');}
function openCheckoutPage(){if(!cart.length){alert('סל הקניות שלך ריק.');return;}closeCartModal();document.getElementById('checkoutModal')?.classList.add('active');toggleCheckoutFields();updateCheckoutSummary();}
function closeCheckoutPage(){document.getElementById('checkoutModal')?.classList.remove('active');}
function openTermsModal(){document.getElementById('termsModal')?.classList.add('active');}
function closeTermsModal(){document.getElementById('termsModal')?.classList.remove('active');}
function openSuccessModal(orderId){const n=document.getElementById('successOrderNumber');if(n)n.innerText=`מספר הזמנה: ${orderId}`;document.getElementById('successModal')?.classList.add('active');}
function closeSuccessModal(){document.getElementById('successModal')?.classList.remove('active');}
function toggleFaq(button){button.parentElement.classList.toggle('active');}
function filterType(){renderProducts();} function filterLevel(){renderProducts();} function filterVariety(){renderProducts();} function filterCatalog(){renderProducts();}

function addSpecialOrderBanner(){const grid=document.getElementById('productsGrid');if(!grid||document.getElementById('specialOrderBanner'))return;const b=document.createElement('div');b.id='specialOrderBanner';b.style.cssText='grid-column:1/-1;text-align:center;padding:18px 22px;margin:8px 0 20px;border:1px solid #d8b657;border-radius:16px;background:linear-gradient(135deg,#fffdf5,#f4ead0);color:#244b37;font-weight:700;box-shadow:0 8px 24px rgba(79,61,22,.10)';b.innerHTML='רוצים סט בהרכב מיוחד או בקשה אחרת? <a href="https://wa.me/972552809503" target="_blank" rel="noopener" style="color:#176b43;text-decoration:underline">פנו אלינו בוואטסאפ</a>';grid.parentElement.insertBefore(b,grid);}
function renderProducts(){const grid=document.getElementById('productsGrid');if(!grid)return;grid.innerHTML='';products.forEach(p=>{const card=document.createElement('div');card.className='product-card reveal product-card-clickable';card.innerHTML=`<div class="product-badge">${p.badge}</div><div class="product-type-ribbon">${p.name}</div><div class="product-img-container"><div class="placeholder-art"><i class="fa-solid ${p.icon}"></i><span>${p.name}</span></div><div class="product-hover-image" style="background-image:linear-gradient(rgba(27,67,50,.10),rgba(18,53,36,.12)),url('8.png')"></div></div><div class="product-info"><h3 class="product-title">${p.name}</h3><p class="product-desc">${p.desc}</p><div class="product-meta">${p.level} · ${p.variety} · משלוח באזור המרכז ₪45</div><div class="product-footer"><span class="product-price">₪${p.price}</span><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><div class="quantity-selector"><button class="qty-btn" onclick="changeProductQty(${p.id},-1,this)">-</button><span class="qty-val" id="qty-${p.id}">1</span><button class="qty-btn" onclick="changeProductQty(${p.id},1,this)">+</button></div><button class="add-to-cart-btn" onclick="addToCart(${p.id})"><i class="fa-solid fa-cart-plus"></i> הוספה לסל</button><button class="direct-checkout-btn" onclick="buyNow(${p.id})"><i class="fa-solid fa-credit-card"></i> מעבר לתשלום</button></div></div></div>`;grid.appendChild(card);});}
function changeProductQty(id,change,btn){const el=btn.parentElement.querySelector('.qty-val');el.innerText=Math.max(1,parseInt(el.innerText||'1')+change);}
function buyNow(id){const p=products.find(x=>x.id===id);if(!p)return;const qty=parseInt(document.getElementById(`qty-${id}`)?.innerText||'1');cart=[{...p,qty}];saveCart();updateCartUI();openCheckoutPage();}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const qty=parseInt(document.getElementById(`qty-${id}`)?.innerText||'1');const e=cart.find(x=>x.id===id);if(e)e.qty+=qty;else cart.push({...p,qty});saveCart();updateCartUI();}
function changeCartItemQty(id,c){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=c;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();updateCartUI();renderCartItems();}
function removeCartItem(id){cart=cart.filter(x=>x.id!==id);saveCart();updateCartUI();renderCartItems();}
function saveCart(){localStorage.setItem('sukkot_cart',JSON.stringify(cart));}
function updateCartUI(){const n=cart.reduce((s,i)=>s+i.qty,0);['cartCount','floatingCartCount'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerText=n;});}
function renderCartItems(){const list=document.getElementById('cartItemsList');if(!list)return;list.innerHTML='';let total=0,count=0;cart.forEach(i=>{total+=i.price*i.qty;count+=i.qty;const r=document.createElement('div');r.className='cart-item';r.innerHTML=`<div class="cart-item-details"><div><div class="cart-item-name">${i.name}</div><div class="cart-item-price">₪${i.price} × ${i.qty} = ₪${i.price*i.qty}</div></div></div><div class="quantity-selector"><button class="qty-btn" onclick="changeCartItemQty(${i.id},-1)">-</button><span class="qty-val">${i.qty}</span><button class="qty-btn" onclick="changeCartItemQty(${i.id},1)">+</button></div><button class="remove-item" onclick="removeCartItem(${i.id})"><i class="fa-solid fa-trash"></i></button>`;list.appendChild(r);});const c=document.getElementById('summaryCount'),t=document.getElementById('summaryTotal');if(c)c.innerText=count;if(t)t.innerText=`₪${total}`;}
function updateCheckoutSummary(){const form=document.getElementById('checkoutForm'),modal=document.getElementById('checkoutModal');if(!form||!modal)return;let s=modal.querySelector('.checkout-order-summary');if(!s){s=document.createElement('div');s.className='checkout-order-summary';form.insertBefore(s,form.firstChild);}const shipping=document.querySelector('input[name="shippingMethod"]:checked')?.value||'איסוף עצמי',ship=shipping==='משלוח'?45:0;const lines=cart.map(i=>`<div class="checkout-summary-row"><span>${i.name}</span><strong>₪${i.price} × ${i.qty} = ₪${i.price*i.qty}</strong></div>`).join('');const subtotal=cart.reduce((a,i)=>a+i.price*i.qty,0);s.innerHTML=`<h3><i class="fa-solid fa-basket-shopping"></i> סיכום ההזמנה</h3>${lines}<div class="checkout-summary-row"><span>${shipping}</span><strong>${ship?'₪'+ship:'ללא תוספת'}</strong></div><div class="checkout-summary-row total"><span>סה״כ לתשלום</span><strong>₪${subtotal+ship}</strong></div>`;}
function toggleCheckoutFields(){const shipping=document.querySelector('input[name="shippingMethod"]:checked')?.value||'איסוף עצמי',delivery=shipping==='משלוח';['custCity','custStreet','custHouse'].forEach(id=>{const e=document.getElementById(id);if(e)e.required=delivery;});updateCheckoutSummary();}
function setCheckoutLoading(v){const b=document.getElementById('submitOrderBtn');if(b){b.disabled=v;b.innerHTML=v?'מעביר לתשלום... <i class="fa-solid fa-circle-notch submit-spinner"></i>':'שליחת הזמנה ואישור <i class="fa-solid fa-paper-plane"></i>';}}
function createSequentialOrderId(){const n=(Number(localStorage.getItem(ORDER_SEQUENCE_KEY))||0)+1;localStorage.setItem(ORDER_SEQUENCE_KEY,String(n));return `SUKKOT-${String(n).padStart(6,'0')}`;}
async function handleCheckout(event){event.preventDefault();if(isSubmittingOrder||!cart.length)return;isSubmittingOrder=true;setCheckoutLoading(true);const orderId=createSequentialOrderId();const val=id=>document.getElementById(id)?.value.trim()||'';const shipping=document.querySelector('input[name="shippingMethod"]:checked')?.value||'איסוף עצמי';const street=val('custStreet'),house=val('custHouse'),apt=val('custApartment'),address=[street,house&&`בית ${house}`,apt&&`דירה ${apt}`].filter(Boolean).join(', ');const total=cart.reduce((s,i)=>s+i.price*i.qty,0)+(shipping==='משלוח'?45:0);const orderData={orderId,customer:{name:val('custName'),phone:val('custPhone'),email:val('custEmail'),notes:val('custNotes'),city:val('custCity'),street,houseNumber:house,apartmentNumber:apt,address},items:cart.map(i=>({id:i.id,sku:i.sku,name:i.name,qty:i.qty,price:i.price,lineTotal:i.qty*i.price})),paid:false,paymentStatus:'waiting_for_payment',orderStatus:'waiting_for_payment',shippingMethod:shipping,totalPrice:total,date:new Date().toISOString()};localStorage.setItem('grow_pending_order_id',orderId);localStorage.setItem('grow_pending_summary',JSON.stringify({orderId,items:orderData.items,shipping,total}));window.saveOrderToFirebase?.(orderData).catch(console.error);closeCheckoutPage();if(window.startGrowPayment)window.startGrowPayment(orderData);else openSuccessModal(orderId);isSubmittingOrder=false;setCheckoutLoading(false);}
function handleContactForm(e){e.preventDefault();alert('תודה על פנייתך! נציג יחזור אליך בהקדם.');e.target.reset();}